#!/usr/bin/env python3
"""Generate lib/wwData.ts from the /tmp/ww-*.json Dune result files.

Run after scripts/ww-research.sh (and the volume/decode/timeseries helpers).
Missing inputs degrade gracefully to empty arrays.
"""
import json, os, datetime

TMP = "/tmp"

def rows(name):
    try:
        return json.load(open(f"{TMP}/ww-{name}.json")).get("result", {}).get("rows", [])
    except Exception:
        return []

daily = [{"block_date": r["block_date"][:10], "txs": int(r["txs"]), "traders": int(r["traders"])} for r in rows("daily")]
traders = [{"trader": r["trader"], "txs": int(r["txs"])} for r in rows("traders")]

praw = rows("pnl")
deltas = [float(r["sol_delta"]) for r in praw]
cum = 0.0
pnl = []
for r in praw:
    cum += float(r["sol_delta"])
    pnl.append({"t": r["block_time"][:19], "cum": round(cum, 4)})
if len(pnl) > 180:
    step = len(pnl) / 180
    keep = [pnl[int(i * step)] for i in range(180)]
    if keep[-1] != pnl[-1]:
        keep.append(pnl[-1])
    pnl = keep

win = sum(1 for d in deltas if d > 0)
loss = sum(1 for d in deltas if d < 0)
traderStats = {
    "txs": len(deltas),
    "solBet": round(-sum(d for d in deltas if d < 0), 4),
    "solReturned": round(sum(d for d in deltas if d > 0), 4),
    "net": round(sum(deltas), 4),
    "biggestWin": round(max(deltas), 4) if deltas else 0,
    "biggestLoss": round(min(deltas), 4) if deltas else 0,
    "winTxs": win, "lossTxs": loss,
    "winRate": round(100 * win / len(deltas), 1) if deltas else 0,
}

pr = [{"t": r["block_time"][:10], "sol": round(float(r["sol_delta"]), 4)} for r in praw]
traderTop = {"wins": sorted(pr, key=lambda x: -x["sol"])[:5], "losses": sorted(pr, key=lambda x: x["sol"])[:5]}

# monthly net PnL from the full per-tx deltas
mon = {}
for r in praw:
    m = r["block_time"][:7]
    mon[m] = mon.get(m, 0.0) + float(r["sol_delta"])
pnlMonthly = [{"month": k, "net": round(v, 4)} for k, v in sorted(mon.items())]

dflow = [{"block_date": r["block_date"][:10], "inflow": round(float(r["inflow"]), 4),
          "outflow": round(float(r["outflow"]), 4), "net": round(float(r["net"]), 4)} for r in rows("devflow")]
platformStats = {
    "programTxs": sum(d["txs"] for d in daily), "activeDays": len(daily),
    "firstDay": daily[0]["block_date"] if daily else "-", "lastDay": daily[-1]["block_date"] if daily else "-",
    "treasuryInflow": round(sum(d["inflow"] for d in dflow), 4),
    "treasuryOutflow": round(sum(d["outflow"] for d in dflow), 4),
    "treasuryNet": round(sum(d["net"] for d in dflow), 4),
}

NAMES = {'28ef8a9a08256a6c': 'buyShares', 'b8a4a910e79ec7c4': 'sellShares',
         '756ca69f9252f6df': 'initializeBattle', '5091d030b75ca870': 'endBattle',
         '82831ded86146ef5': 'claimShares', 'bd54558eb1c83916': 'initializeMints'}
dec = {}
for r in rows("decode"):
    n = NAMES.get((r.get("disc") or "").lower())
    if n:
        dec[n] = {"calls": int(r["calls"]), "signers": int(r["signers"])}
g = lambda k: dec.get(k, {}).get("calls", 0)
program = {"battlesCreated": g("initializeBattle"), "battlesSettled": g("endBattle"),
           "buys": g("buyShares"), "sells": g("sellShares"), "claims": g("claimShares"),
           "uniqueTraders": dec.get("buyShares", {}).get("signers", 0)}

tl = {}
for r in rows("timeseries"):
    n = NAMES.get((r.get("disc") or "").lower())
    if not n:
        continue
    d = r["block_date"][:10]
    c = int(r["c"])
    e = tl.setdefault(d, {"block_date": d, "battles": 0, "trades": 0, "claims": 0})
    if n == "initializeBattle":
        e["battles"] += c
    elif n in ("buyShares", "sellShares"):
        e["trades"] += c
    elif n == "claimShares":
        e["claims"] += c
timeline = [tl[k] for k in sorted(tl)]

dayvol = [{"block_date": r["block_date"][:10], "vol": round(float(r["buy_volume"]), 4), "buys": int(r["buys"])} for r in rows("dayvol")]
volboard = [{"trader": r["trader"], "vol": round(float(r["volume"]), 4), "buys": int(r["buys"])} for r in rows("volboard")]
volume = {"total": round(sum(d["vol"] for d in dayvol), 4), "series": dayvol, "board": volboard}

stamp = os.environ.get("WW_STAMP") or datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%MZ")

def js(o):
    return json.dumps(o, separators=(",", ":"))

ts = f'''// WaveWarZ on-chain analytics snapshot. Generated by scripts/ww-gen.py from
// Dune queries on program 9TUfEHvk5fN5vogtQyrefgNqzKy2Bqb4nWVhSFUg2fYo.

export interface DailyActivity {{ block_date: string; txs: number; traders: number; }}
export interface TraderRank {{ trader: string; txs: number; }}
export interface PnlPoint {{ t: string; cum: number; }}
export interface DevFlow {{ block_date: string; inflow: number; outflow: number; net: number; }}
export interface TraderStats {{ txs: number; solBet: number; solReturned: number; net: number; biggestWin: number; biggestLoss: number; winTxs: number; lossTxs: number; winRate: number; }}
export interface PlatformStats {{ programTxs: number; activeDays: number; firstDay: string; lastDay: string; treasuryInflow: number; treasuryOutflow: number; treasuryNet: number; }}
export interface ProgramSummary {{ battlesCreated: number; battlesSettled: number; buys: number; sells: number; claims: number; uniqueTraders: number; }}
export interface TimelinePoint {{ block_date: string; battles: number; trades: number; claims: number; }}
export interface TopMove {{ t: string; sol: number; }}
export interface TraderTop {{ wins: TopMove[]; losses: TopMove[]; }}
export interface MonthPnl {{ month: string; net: number; }}
export interface VolPoint {{ block_date: string; vol: number; buys: number; }}
export interface VolRank {{ trader: string; vol: number; buys: number; }}
export interface Volume {{ total: number; series: VolPoint[]; board: VolRank[]; }}
export interface WwSnapshot {{
  generatedAt: string;
  daily: DailyActivity[];
  traders: TraderRank[];
  pnl: PnlPoint[];
  devflow: DevFlow[];
  traderStats: TraderStats;
  platformStats: PlatformStats;
  program: ProgramSummary;
  timeline: TimelinePoint[];
  traderTop: TraderTop;
  pnlMonthly: MonthPnl[];
  volume: Volume;
}}

export const WW: WwSnapshot = {{
  generatedAt: {js(stamp)},
  daily: {js(daily)},
  traders: {js(traders)},
  pnl: {js(pnl)},
  devflow: {js(dflow)},
  traderStats: {js(traderStats)},
  platformStats: {js(platformStats)},
  program: {js(program)},
  timeline: {js(timeline)},
  traderTop: {js(traderTop)},
  pnlMonthly: {js(pnlMonthly)},
  volume: {js(volume)},
}};
'''
open("lib/wwData.ts", "w").write(ts)
print(f"wrote lib/wwData.ts | monthly={len(pnlMonthly)} volume_total={volume['total']} volboard={len(volboard)}")
